<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fsm</string>
	</array>
	<key>name</key>
	<string>Tekkotsu</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Highlight for a $nodeclass declaration</string>
			<key>match</key>
			<string>(^|\s+)\$nodeclass\s+</string>
			<key>name</key>
			<string>storage.type.nodeclass.fsm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Highlights the $provide keyword</string>
			<key>match</key>
			<string>(^|\s+)\$provide\s+</string>
			<key>name</key>
			<string>keyword.other.directive.provide.fsm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.directive.reference.fsm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highlights the $reference keyword</string>
			<key>match</key>
			<string>(^|\s*)(\$reference)\s+([A-Z][a-zA-Z0-9_]*)\:\:([a-z][a-zA-Z0-9_]*);\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.doStart.fsm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highlights the "doStart" portion in shorthand doStart declaration</string>
			<key>match</key>
			<string>\:\s+(doStart)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fsm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Higlights $setup, $setupmachine, and $statemachine</string>
			<key>match</key>
			<string>(^|\s+)(\$((setup(machine)?)|(statemachine)))\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fsm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.fsm</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.specificTransValue.fsm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highlights transitions</string>
			<key>match</key>
			<string>\s+(=S&lt;([a-zA-Z0-9_\:]+)&gt;(\(([a-zA-Z0-9_]+)\))?=&gt;)\s+</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fsm</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.specificTransValue.fsm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Highlights transitions</string>
			<key>match</key>
			<string>\s+(=[A-Z]+(\(([a-zA-Z0-9_]+)\))?=&gt;)\s+</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fsm</string>
	<key>uuid</key>
	<string>dd8b13f7-9e38-4809-8cbf-23a48921c3c2</string>
</dict>
</plist>
